CREATE DATABASE IF NOT EXISTS hackaton CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hackaton;

CREATE TABLE IF NOT EXISTS Jogadores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nomeusuario VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  faseatual INT DEFAULT 1,
  pontos INT DEFAULT 0,
  quizacertos INT DEFAULT 0,
  quizerros INT DEFAULT 0,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ProgressoFases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  jogador_id INT NOT NULL,
  fasenumero INT NOT NULL,
  concluida TINYINT(1) DEFAULT 0,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (jogador_id) REFERENCES Jogadores(id) ON DELETE CASCADE
);
